Unify allow device credential API
SelfLender/react-native-biometrics pull request #185
Opened 2022-05-19 18:46 UTC by jayfunk

The majority of the legacy functions required providing the option `allowDeviceCredentials` set to `true` in order to fully enable device credentials as a fallback/alternative. The problem with this approach is that all of the function calls had to ensure the same value was set, otherwise you might encounter issues with the biometric process. In order to ensure the same setting was used across all of the calls it seemed more straight forward to introduce a class for controlling the device credential state. The legacy API is still accessible and only requires a minor modification to any existing use cases. The one caveat is that the legacy API does NOT support the device feature. This can only be enabled when using the new API.

2022-05-24 14:48 UTC, davidy3k requested changes

2022-05-24 14:53 UTC, jayfunk commented on README.md
> +if (biometryType === BiometryTypes.FaceID) {
👍

2022-05-24 14:53 UTC, jayfunk commented on index.ts
> +export type BiometryType = 'TouchID' | 'FaceID' | 'Biometrics'
This is a Typescript type that is only used for instances where the consumer is using typescript.

2022-05-26 08:42 UTC, davidy3k approved these changes

2022-05-31 18:59 UTC, NappyPirate approved these changes

2022-05-31 19:02 UTC, merged